### ISSUE TITLE
Update cookbook on opscode

### ISSUE THREAD

**Issue by VoidAndAny** [danhart/locale-gen#4]
Can you please update your cookbook on opscode site ?
On github we have 0.03 which works fine but on opscode community cookbooks site it is 0.01 which is buggy.

Its important because if someone use Berkshelf (like me) it will download your cookbok from opscode by default.

Thanks

**Comment by aalmenar** [comment]
I support this. The one on opscode its different from this one.

**Comment by danhart** [comment]
I have updated opscode to version 0.0.3. Will look at integrating 0.0.4 with master soon.

Thanks.
